# Generated by Django 4.2.7 on 2025-12-30 05:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('context', models.TextField(blank=True, null=True, verbose_name='文脈')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'ノード',
                'verbose_name_plural': 'ノード',
                'db_table': 'nodes',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='プロジェクト名')),
                ('status', models.CharField(choices=[('active', 'アクティブ'), ('pending', 'ペンディング'), ('completed', '完了')], default='active', max_length=20, verbose_name='状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'プロジェクト',
                'verbose_name_plural': 'プロジェクト',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='周番号')),
                ('note', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='projects.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': '周',
                'verbose_name_plural': '周',
                'db_table': 'rounds',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_type', models.CharField(choices=[('overview', '俯瞰'), ('extract', '要素抽出'), ('flow', '流れ構築'), ('mvp', '最小仕様'), ('expand', '拡張余地')], max_length=20, verbose_name='ステップ種別')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='projects.project', verbose_name='プロジェクト')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='projects.round', verbose_name='周')),
            ],
            options={
                'verbose_name': '思考プロセスのステップ',
                'verbose_name_plural': '思考プロセスのステップ',
                'db_table': 'process_steps',
            },
        ),
        migrations.CreateModel(
            name='NodeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=1, default=0.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)], verbose_name='重み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='projects.node', verbose_name='元ノード')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='projects.node', verbose_name='先ノード')),
            ],
            options={
                'verbose_name': 'ノードリンク',
                'verbose_name_plural': 'ノードリンク',
                'db_table': 'node_links',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='projects.project', verbose_name='プロジェクト'),
        ),
        migrations.AddField(
            model_name='node',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='projects.round', verbose_name='周'),
        ),
        migrations.AddField(
            model_name='node',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='projects.processstep', verbose_name='ステップ'),
        ),
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['project'], name='idx_rounds_project_id'),
        ),
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['project', 'round_number'], name='idx_rounds_project_round'),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('project', 'round_number')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='idx_projects_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='idx_projects_created_at'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user'], name='idx_projects_user'),
        ),
        migrations.AddIndex(
            model_name='processstep',
            index=models.Index(fields=['project'], name='idx_process_steps_project_id'),
        ),
        migrations.AddIndex(
            model_name='processstep',
            index=models.Index(fields=['round'], name='idx_process_steps_round_id'),
        ),
        migrations.AddIndex(
            model_name='processstep',
            index=models.Index(fields=['round', 'step_type'], name='idx_process_steps_round_step'),
        ),
        migrations.AlterUniqueTogether(
            name='processstep',
            unique_together={('round', 'step_type')},
        ),
        migrations.AddIndex(
            model_name='nodelink',
            index=models.Index(fields=['from_node'], name='idx_node_links_from_node'),
        ),
        migrations.AddIndex(
            model_name='nodelink',
            index=models.Index(fields=['to_node'], name='idx_node_links_to_node'),
        ),
        migrations.AddConstraint(
            model_name='nodelink',
            constraint=models.CheckConstraint(check=models.Q(('from_node', models.F('to_node')), _negated=True), name='check_different_nodes'),
        ),
        migrations.AlterUniqueTogether(
            name='nodelink',
            unique_together={('from_node', 'to_node')},
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['project'], name='idx_nodes_project_id'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['round'], name='idx_nodes_round_id'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['step'], name='idx_nodes_step_id'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['title'], name='idx_nodes_title'),
        ),
    ]
